template_path: remote-templates/essentials.yaml
stack_name: essentials
dependencies:
  - bootstrap
parameters:
  OperatorEmail: aws.organizations@sagebase.org
  VpcPeeringRequesterAwsAccountId: !ssm /infra/AdmincentralAwsAccountId
hooks:
  before_update:
    - !cmd "curl https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/master/templates/essentials.yaml --create-dirs -o remote-templates/essentials.yaml"
