template_path: remote/rotate-credentials.yaml
stack_name: rotate-credentials
dependencies:
  - prod/bootstrap.yaml
parameters:
  DisableKeys: 'true'
  SendEmail: 'true'
  SenderEmail: 'it@sagebase.org'
  SendReport: 'true'
hooks:
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/rotate-credentials.yaml --create-dirs -o templates/remote/rotate-credentials.yaml"
