project_code: "sage-bionetworks"
# profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
template_key_prefix: {{ environment_variable.GITHUB_REF | default("testing") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
service_catalog_library: "service-catalog-library"
j2_environment:
  extensions:
    - jinja2_from_json_extension
    - FromJsonExtension
