template_path: "remote/cfn-s3objects-macro.yaml"
stack_name: "cfn-s3objects-macro"
dependencies:
  - "prod/bootstrap.yaml"
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/cfn-s3objects-macro/master/cfn-s3objects-macro.yaml --create-dirs -o templates/remote/cfn-s3objects-macro.yaml"
