template:
  path: "sc-product-ec2-linux-docker.j2"
stack_name: "khai-sc-product-ec2-linux-docker"
stack_tags:
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "khai/khai-sc-portfolio-ec2.yaml"
  - "khai/khai-sc-portfolio-ec2-external.yaml"
#  - "khai/khai-sc-ec2-actions.yaml"
parameters:
  ProductName: "EC2: Linux Docker"
  ReplaceProvisioningArtifacts: "true"
sceptre_user_data:
  # force cloudformation to update stack by setting a random number to the latest product's description
  ProvisioningArtifactParameters: |
    - Description: 'Baseline release.'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.18/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.18'
    - Description: 'Increase EBS volume size limit to 5 TB.'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.19/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.19'
    - Description: 'Reduce instance types'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.21/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.21'
    - Description: 'Add instance types x2gd, g4dn, and i3en.'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.22/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.22'
    - Description: 'Update for AWS VPN.'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.36/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.36'
    - Description: 'Update base AMI.'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.37/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.37'
    - Description: 'Propagate instance tags to attached volumes'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.40/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.1.40'
    - Description: 'Change to less costly volume type {{ range(1, 10000) | random }}'
      Info:
        LoadTemplateFromURL: 'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.2.9/ec2/sc-ec2-linux-docker.yaml'
      Name: 'v1.2.9'
