template_path: remote/vpc.yaml
stack_name: synapse-ops-vpc-v2
parameters:
  VpcSubnetPrefix: "10.30"
  VpcName: synapse-ops-vpc-v2
  PrivateSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
  PublicSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/vpc.yaml -N -P templates/remote"
