template:
  type: "http"
  url: "https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.8.6/templates/Cloudwatch/Link-Management-Account.yaml"
stack_name: "sagebase-CloudWatcDashboard-LinkManagementAccount"
stack_tags:
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/CloudWatch-CrossAccountSharingRole-AccountList.yaml"
parameters:
  MonitoringAccountId: "767397888168"
  SinkIdentifier: "6046cc13-135d-4e41-ae56-63327a7a7b8c"
