template:
  type: http
  url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.7.4/templates/IAM/github-oidc-provider.j2
stack_name: github-oidc-synapse-login
parameters:
  ManagedPolicyArns:
    - "arn:aws:iam::aws:policy/AdministratorAccess"
  ThumbprintList:
    - "6938fd4d98bab03faadb97b34396831e3780aea1"
  GitHubOrg: "Sage-Bionetworks"
  MaxSessionDuration: "7200"
sceptre_user_data:
  Repositories:
    - name: "synapse-login-aws-infra"
      branch: "*"