template_path: remote/peer-route-config.yaml
stack_name: peer-vpn-cesspoolvpc
dependencies:
  - develop/cesspoolvpc.yaml
parameters:
  PeeringConnectionId: "pcx-052484218893705d9"
  VpcPrivateRouteTable: "rtb-094f2336c06807361"
  VpcPublicRouteTable: "rtb-036d799b77abcd1fb"
  VpnCidr: "10.1.0.0/16"
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_url}}/master/peer-route-config.yaml -N -P templates/remote"
