template:
  path: "sc-portfolio-s3-basic.yaml"
stack_name: "sc-portfolio-s3-basic"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "develop/sc-s3-launchrole.yaml"
  - "develop/sc-enduser-iam.yaml"
