template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.2/VPC/vpc-mini.yaml
stack_name: scriptrunnervpc
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - develop/bootstrap.yaml
parameters:
  VpcSubnetPrefix: "10.255.39"
  VpcName: "scriptrunnervpc"
