template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/cfn-cr-oidc-idp/0.2.0/cfn-cr-oidc-idp.yaml
stack_name: synapse-oidc-idp
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Url: "https://repo-prod.prod.sagebase.org/auth/v1"
  ClientIDList: "100055"
  ThumbprintList: "9e99a48a9960b14926bb7f3b02e22da2b0ab7280"
