template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.0/transit-gateway-spoke.yaml
stack_name: "tgw-spoke-cesspoolvpc"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "develop/cesspoolvpc.yaml"
parameters:
  TransitGatewayEndpointCidr: "10.50.0.0/16"
  VpcRouteTableId: !stack_output_external cesspoolvpc::PrivateRouteTable
  VpcId: !stack_output_external cesspoolvpc::VPCId
  SubnetIds:
    - !stack_output_external cesspoolvpc::PrivateSubnet
    - !stack_output_external cesspoolvpc::PrivateSubnet1
    - !stack_output_external cesspoolvpc::PrivateSubnet2
  # shared TGW, https://github.com/Sage-Bionetworks/transit-infra/blob/master/templates/transit-gateway.j2
  TransitGatewayId: "tgw-0004e7e3454cacac5"
