template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.0/peer-route-config.yaml
stack_name: peer-vpn-stridespoolvpc
dependencies:
  - strides/stridespoolvpc.yaml
parameters:
  PeeringConnectionId: "pcx-0631346ea5ff7181c"  # org-sagebase-strides peering connection ID
  VpcPrivateRouteTable: !stack_output_external stridespoolvpc::PrivateRouteTable
  VpcPublicRouteTable: !stack_output_external stridespoolvpc::PublicRouteTable
  VpnCidr: !stack_output_external stridespoolvpc::VpnCidr      # org-sagebase-admincentral sophos-utm VPN CIDR
