template:
  path: "sc-ec2-action-associations.yaml"
stack_name: "sc-product-assoc-ec2-windows-jumpcloud"
stack_tags:
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "strides/sc-product-ec2-windows-jumpcloud.yaml"
parameters:
  ProductId: !stack_output_external sc-product-ec2-windows-jumpcloud::ProductId
