template_path: "sc-product-ec2-linux-jumpcloud.j2"
stack_name: "sc-product-ec2-linux-jumpcloud"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "strides/sc-portfolio-ec2.yaml"
  - "strides/sc-ec2-actions.yaml"
  - "strides/sc-portfolio-ec2-external.yaml"
sceptre_user_data:
  # force cloudformation to update stack by setting a random number to the latest product's description
  ProvisioningArtifactParameters: |
    - Description: 'Baseline version.'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.0.0/ec2/sc-ec2-linux-jumpcloud-v1.0.0.yaml'
      Name: 'v1.0.0'
    - Description: 'Includes fix for a linux relocation error.'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.0.1/ec2/sc-ec2-linux-jumpcloud-v1.0.1.yaml'
      Name: 'v1.0.1'
    - Description: 'Fix to support multiple portfolios'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.0.2/ec2/sc-ec2-linux-jumpcloud-v1.0.2.yaml'
      Name: 'v1.0.2'
    - Description: 'Remove Jumpcloud Integration.'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.2/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.2'
    - Description: 'Update Cloudformation hooks'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.3/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.3'
    - Description: 'Use SynapseTagger'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.7/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.7'
    - Description: 'Remove VpcName input'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.8/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.8'
    - Description: 'Update for strides'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.9/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.9'
    - Description: 'Include params in mapping'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.10/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.10'
    - Description: 'Fix policies'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.13/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.13'
    - Description: !Sub 'Restore set_env_vars. {{ range(1, 10000) | random }}'
      Info:
        LoadTemplateFromURL: !Sub '${RepoRootURL}/v1.1.14/ec2/sc-ec2-linux-jumpcloud.yaml'
      Name: 'v1.1.14'
