template:
  path: "sc-portfolio-ec2.yaml"
stack_name: "sc-portfolio-ec2"
dependencies:
  - "strides/sc-ec2vpc-launchrole.yaml"
  - "strides/sc-enduser-iam.yaml"
parameters:
  PorfolioName: "Sage EC2 Porfolio"
  PorfolioDescription: "EC2 Products for Sage Bionetworks staff"
