template:
  path: "sc-product-s3-synapse.j2"
stack_name: "sc-product-s3-synapse"
stack_tags:
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "strides/sc-portfolio-s3-basic.yaml"
parameters:
  ProvisioningArtifactGuidance: "DEPRECATED"
  ProvisioningArtifactAction: "ALL_EXCEPT_LATEST"
sceptre_user_data:
  # force cloudformation to update stack by setting a random number to the latest product's description
  ProvisioningArtifactParameters: |
    - Description: 'Baseline version.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.0.0/s3/sc-s3-synapse-ra-v1.0.0.yaml'
      Name: 'v1.0.0'
    - Description: 'Remove SynapseProdARN parameter.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.0.1/s3/sc-s3-synapse-ra-v1.0.1.yaml'
      Name: 'v1.0.1'
    - Description: 'Fix resource contention bug with S3 custom resources'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.0.2/s3/sc-s3-synapse-ra-v1.0.2.yaml'
      Name: 'v1.0.2'
    - Description: 'Allow multiple synapse bucket owners'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.6/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.6'
    - Description: 'Use SynapseTagger'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.7/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.7'
    - Description: 'Remove VpcName input'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.8/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.8'
    - Description: 'Update for strides'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.9/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.9'
    - Description: 'Include params in mapping.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.10/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.10'
    - Description:  'Include option to restrict bucket downloads to same region.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.15/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.15'
    - Description:  'Fix cross account access.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.20/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.20'
    - Description:  'Retain bucket on SC product termination.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.23/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.23'
    - Description:  'Enable intelligent tiering.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.24/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.24'
    - Description:  'Remove option to add arbitrary IAM ARN.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.25/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.25'
    - Description:  'Pin cfn-cr-same-region-bucket-download lambda.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.33/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.33'
    - Description:  'Disable bucket ACLs.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.38/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.38'
    - Description:  'Remove bucket ACL setting.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.1.39/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.1.39'
    - Description:  'Update cfn-cr-same-region-bucket-download python version.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.3.8/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.3.8'
    - Description:  'Update cfn-cr-same-region-bucket-download dependencies.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.4.4/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.4.4'
    - Description:  'Update cfn-cr-same-region-bucket-download dependencies.'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.4.7/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.4.7'
    - Description:  'Resolves IT-4074. {{ range(1, 10000) | random }}'
      Info:
        LoadTemplateFromURL:  'https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/{{stack_group_config.service_catalog_library}}/v1.4.9/s3/sc-s3-synapse-ra.yaml'
      Name: 'v1.4.9'
