template_path: remote/vpc.yaml
stack_name: stridespoolvpc
dependencies:
  - strides/bootstrap.yaml
parameters:
  VpcSubnetPrefix: "10.49"
  VpcName: stridespoolvpc
hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/vpc.yaml -O templates/remote/vpc.yaml"
