template:
  path: VPCPeer.yaml
stack_name: peering-sandcastlevpc
parameters:
  PeerVPC: vpc-0e9b80dc470a797d5
  PeerVPCOwner: !ssm /infra/SandboxAwsAccountId
  PeerVPCCIDR: 10.23.0.0/16
  PeerRoleName: essentials-VPCPeeringAuthorizerRole-ZEGJ99TU4YVM
