template:
  path: VPCPeer.yaml
stack_name: peering-internalpoolvpc
parameters:
  PeerVPC: "vpc-0d4b8ad691df536c6"
  PeerVPCOwner: "237179673806"  # org-sagebase-scipoolprod
  PeerVPCCIDR: "10.41.0.0/16"
  PeerRoleName: "essentials-VPCPeeringAuthorizerRole-3USPVUYZWERZ"
