template:
  path: VPCPeer.yaml
stack_name: peering-bridgeserver2-develop-vpc
parameters:
  PeerVPC: vpc-08ad2ebc1c49963b8
  PeerVPCOwner: !ssm /infra/BridgeDevAwsAccountId
  PeerVPCCIDR: 172.48.0.0/16
  PeerRoleName: bridge-VPCPeeringAuthorizerRole-13KSQX7XGYVAJ
