template:
  path: VPCPeer.yaml
stack_name: peering-bridge-aux
parameters:
  PeerVPC: vpc-e9335a92
  PeerVPCOwner: !ssm /infra/BridgeDevAwsAccountId
  PeerVPCCIDR: 172.51.0.0/16
  PeerRoleName: bridge-VPCPeeringAuthorizerRole-13KSQX7XGYVAJ
