template_path: "remote/AccountAlertTopics.yaml"
stack_name: "AccountAlertTopics"
dependencies:
  - "prod/bootstrap.yaml"
parameters:
  InitialSubscriberEmail: "aws.imagecentral@sagebase.org"
  EnableSubscriberSMS: "false"
  BillingThreshold: "1000"
  DeployLambda: "true"
  SlackWebhookURL: !ssm "/infra/SlackWebhookUrl"
  SlackChannel: "#infra-notices"
hooks:
  before_create:
    - !cmd "wget https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/AccountAlertTopics.yaml -N -P templates/remote"
  before_update:
    - !cmd "wget https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/AccountAlertTopics.yaml -N -P templates/remote"
