template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.0/transit-gateway-spoke.yaml
stack_name: "tgw-spoke-BridgeServer2-vpc"
stack_tags:
  Department: "Platform"
  Project: "Bridge"
  OwnerEmail: "bridgeIT@sagebase.org"
dependencies:
  - "prod/BridgeServer2-vpc.yaml"
parameters:
  TransitGatewayEndpointCidr: "10.50.0.0/16"
  VpcRouteTableId: !stack_output_external BridgeServer2-vpc::PrivateRouteTable
  VpcId: !stack_output_external BridgeServer2-vpc::VPCId
  SubnetIds:
    - !stack_output_external BridgeServer2-vpc::PrivateSubnet
    - !stack_output_external BridgeServer2-vpc::PrivateSubnet1
    - !stack_output_external BridgeServer2-vpc::PrivateSubnet2
  # shared TGW, https://github.com/Sage-Bionetworks/transit-infra/blob/master/templates/transit-gateway.j2
  TransitGatewayId: "tgw-0004e7e3454cacac5"
