template_path: remote/gateway-vpc-endpoint.yaml
stack_name: s3-computevpc-gateway-vpc-endpoint
dependencies:
  - prod/computevpc.yaml
parameters:
  VpcName: computevpc
  ServiceName: com.amazonaws.us-east-1.s3
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/gateway-vpc-endpoint.yaml --create-dirs -o templates/remote/gateway-vpc-endpoint.yaml"
