template_path: remote/vpc.yaml
stack_name: snowflakevpc
parameters:
  VpcSubnetPrefix: "10.25"
  VpcName: snowflakevpc
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/vpc.yaml --create-dirs -o templates/remote/vpc.yaml"
