template:
  type: http
  url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.10.6/templates/essentials.yaml
stack_name: "essentials"
dependencies:
  - "prod/bootstrap.yaml"
parameters:
  KmsInfraKeyPrincipals:
    - "arn:aws:iam::531805629419:root"
    - !stack_output_external "bootstrap::AWSIAMSsmParamLambdaExecutionRoleArn"
    - !stack_output_external "sagebase-github-oidc-sage-bionetworks-it::ProviderRoleArn"
