template:
  type: http
  path: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/rotate-credentials/master/rotate-credentials.yaml
stack_name: "rotate-credentials"
dependencies:
  - "prod/bootstrap.yaml"
parameters:
  DisableKeys: "true"
  SendEmail: "true"
  SenderEmail: "it@sagebase.org"
  SendReport: "true"
