template:
  type: http
  url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.6.3/templates/essentials.yaml
stack_name: essentials
dependencies:
  - prod/bootstrap.yaml
parameters:
  VpcPeeringRequesterAwsAccountId: !ssm /infra/AdmincentralAwsAccountId
