template_path: remote/peer-route-config.yaml
stack_name: peer-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-9fcc09f7
  VpcPrivateRouteTable: rtb-0093237c
  VpcPublicRouteTable: rtb-f0aa1a8c
  VpnCidr: 10.1.0.0/16
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_url}}/master/peer-route-config.yaml -N -P templates/remote"
