template_path: remote/peer-route-config.yaml
stack_name: peer-vpc-admincentral
parameters:
  PeeringConnectionId: pcx-9fcc09f7
  VpcPrivateRouteTable: rtb-0093237c
  VpcPublicRouteTable: rtb-f0aa1a8c
  VpnCidr: 10.1.0.0/16
hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/peer-route-config.yaml -O templates/remote/peer-route-config.yaml"
