template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.9.1/vpc.yaml
stack_name: vpc
parameters:
  VpcSubnetPrefix: "10.11"
  VpcName: sagevpc
  PrivateSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
  PublicSubnetZones: "us-east-1c,us-east-1d,us-east-1e"
  IncludeBastianSecurityGroup: "false"
  IncludeOpenSearchServerlessEndpoint: "true"
