template:
  path: "sc-portfolio-ec2-external.yaml"
stack_name: "sc-portfolio-ec2-external"
dependencies:
  - "prod/sc-ec2vpc-launchrole.yaml"
  - "prod/sc-enduser-iam.yaml"
parameters:
  PorfolioName: "Collaborator EC2 Porfolio"
  PorfolioDescription: "EC2 Products for Sage Bionetworks collaborators"
