template_path: remote/sumologic-role.yaml
stack_name: sumologic-role-s3config
dependencies:
  - prod/essentials.yaml
parameters:
  ExternalID: !ssm /infra/SumologicExternalID
  Actions: 's3:GetObject,s3:GetObjectVersion,s3:ListBucketVersions,s3:ListBucket'
  Resource: "arn:aws:s3:::essentials-awss3configbucket-9n8wjykhvr5z"
hooks:
  before_launch:
    - !cmd "wget {{stack_group_config.aws_infra_url}}/master/sumologic-role.yaml -N -P templates/remote"
