template_path: remote/s3-redirector.yaml
stack_name: vpn-sageit-org-redirector
dependencies:
  - prod/sageit-org-acm-cert.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  # the endpoint we are redirecting from
  SourceHostName: "vpn.sageit.org"
  SourceAcmCertificateArn: !stack_output_external "sageit-org-acm-cert::CertificateArn"
  # ID of the sageit.org zone (in sageit account)
  SourceHostedZoneId: "Z0478495257GEB73WFM63"
  # the endpoint we are redirecting to (AWS VPN client self service)
  TargetHostName: "self-service.clientvpn.amazonaws.com"
  # and a path to our specific config
  TargetKey: "endpoints/cvpn-endpoint-055bd9db65af09d63"
hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/s3-redirector.yaml -N -P templates/remote"
