template_path: "sc-ec2-action-associations.yaml"
stack_name: "sc-product-assoc-ec2-linux-jumpcloud-notebook"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "bmgfki/sc-product-ec2-linux-jumpcloud-notebook.yaml"
  - "bmgfki/sc-product-ec2-linux-notebook-write-to-ssm-policy.yaml"

parameters:
  ProductId: !stack_output_external sc-product-ec2-linux-jumpcloud-notebook::ProductId
