template:
  type: http
  url: https://raw.githubusercontent.com/Sage-Bionetworks/aws-infra/v0.7.5/templates/IAM/oidc-provider.yaml
stack_name: github-oidc-provider
parameters:
  ManagedPolicyArns:
    - "arn:aws:iam::aws:policy/AdministratorAccess"
  ThumbprintList:
    - "6938fd4d98bab03faadb97b34396831e3780aea1"
  Url: "https://token.actions.githubusercontent.com"
