template:
  path: "jumpcloud-idp.yaml"
stack_name: "jumpcloud-idp"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  AdminMetadata: !file_contents idp/jumpcloud/strides-ampad-workflows-admin.xml
  AuditorMetadata: !file_contents idp/jumpcloud/strides-ampad-workflows-auditor.xml
  ViewerMetadata: !file_contents idp/jumpcloud/strides-ampad-workflows-viewer.xml
dependencies:
  - "prod/cfn-cr-saml-provider.yaml"
