# Configured like WorkflowsNextflowCIServiceAccounts in org-formation/600-access/_tasks.yaml
template:
  type: http
  url: https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/v0.3.4/templates/IAM/service-account.yaml
stack_name: "workflows-nextflow-ci-service-account"
parameters:
  ManagedPolicyArns:
    - arn:aws:iam::aws:policy/AdministratorAccess
